[Icon Theme]
Name=DesktopConfig
Comment=Local configured icon theme
Inherits=GartoonReduxUpdated,oxygen,breeze
Directories=actions,apps,categories,devices,places,mimetypes,system-overwrite,special

[actions]
Context=Actions
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[apps]
Context=Applications
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[categories]
Context=Categories
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[devices]
Context=Devices
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[places]
Context=Places
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[mimetypes]
Context=MimeTypes
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[system-overwrite]
Type=Scalable
Size=128
MinSize=1
MaxSize=512

[special]
Type=Scalable
Size=128
MinSize=1
MaxSize=512
